### PR TITLE
prusa mk3 sync

### PR DESCRIPTION
**Pull request by guykuo**

### CODE REVIEW

**Comment by shro70** [comment]
Do you plan to update to 3.9 too ? Thx

**Comment by guykuo** [comment]
Yes, but that is really on back burner. Too busy right now with COVID-19 project

bunnyPAPR.com

**Comment by shro70** [comment]
Ok thanks. I edited (steps, stallguard and current) the 3.9 to make it work with my OMC 0.9 setup. It work but not as good as yours.
Have a nice day .

Oh and nice project . Good job as always

**Comment by shyblower** [comment]
You may also take a look at my repo in the meantime
https://github.com/shyblower/Prusa-Firmware
It's cleanly rebased upon 3.9.0.

It optionally supports OMC 17HM15-0904S steppers for X and Y Axis and the MK3 Bondtech extruder upgrade. You can select your setup in the header of Configuration_prusa.h. 

I've copy/pasted a lot from Kuo's fork but finely tuned the stepper driver parameters for the OMC motor since I had a lot of false crash detects and rehomings with Kuo's values. It literally took me weeks to achieve a rock solid result.

I've now been printing successfully for a few months without a singe problem arising from the motors at speeds up to about 200 mm/s. Usually I use something like  70/140/180 for outside/inside/travel which outputs perfect prints without VFAs or other defects.

**Comment by shro70** [comment]
Great news. I will try your FW this afternoon.

**Pull request merged**
