### PR TITLE
Added skelestruder support to Mk3S variant, updated MMU load lengths …

### PR DESCRIPTION
**Pull request by guykuo**
…for skelestruder.

### CODE REVIEW

**Comment by cggorman** [comment]
Mr Kuo,

I'm sorry this is in the wrong place. I'm new to Git and don't yet understand how to use it properly.

I'm finalizing my Bunny-N-Bear .9 build and have a few questions...

I have a 56:16 BNBSX with Mosquito Magnum, Moons .9 steppers on X & Y, and MMU2.

Is there a branch that supports this combo? If so, which?

While attempting to compile the .9 support branch I see 3 commented-out lines to define steps per unit but see no mention of altering (uncommenting) any them. Is this an oversight in the documention? I feel like the define tag on these commented lines means one of them should be uncommented but I've never done this before.

Any help is appreciated!  The hardware is well inside my wheelhouse but the software is new territory for me.

**Comment by guykuo** [comment]
In Configuration_prusa.h see the parts in bold. I am assuming you have Slice thermistor and heater so those defines are uncommented.

Don't mess with those three commented out lines that are AFTER  the line that says. 

//====== Kuo End of defines one normally needs to change ======

If you uncomment any of those three, you potentially override the step settings I have automatically set up with just your selecting the extruder gearing.





====================== end of segment one of this response ===============


/*------------------------------------
 AXIS SETTINGS
 *------------------------------------*/
//Geared extruders now set for lower microstepping to avoid overruning EINSY during fast retracts or MMU2S filament moves. 
//Factory reset and delete all data after installing this firmware. Otherwise EEPROM settings override settings in this firmware.
//After installing this firmware, send M350 and M92 commands to force correct micro-stepping and e-step rates. M350 must be first
//because M350 command will sometimes alter existing M92 setting
//
//e-steps values for M92 depend on your extruder gearing.
//xxx = 280 for non-geared extruder
//xxx = 415 for BMG extruder (special Bondtech compensated value)
//xxx = 420 for 3:1 extruder
//xxx = 473 for BNBSX with 54:16 gearing
//xxx = 490 for BNBSX, Short Ears, Skelestruder with 56:16 gearing
//
//non-geared extruder, 1.8 degree motor
//M350 E32
//M92 E280
//M500
//
//non-geared extruder, 0.9 degree motor
//M350 E16
//M92 E280
//M500
//
//geared extruder, 1.8 degree motor
//M350 E16
//M92 Exxx
//M500
//
//geared extruder, 0.9 degree motor
//M350 E8
//M92 Exxx
//M500
//
//Follow with power off/on and M503 to verify settings are correct.

//====== Kuo Uncommented def(s) below specify 0.9 degree stepper motors on x, y, z, e axis
//Motors used should be 1 amp or lower current rating to avoid overheating TMC2130 drivers in Stealthchop.
//Kuo recommended 0.9 degree motors for X, Y, or direct drive E are Moons MS17HA2P4100 or OMC 17HM15-0904S 
//
**#define X_AXIS_MOTOR_09 //kuo exper X axis
#define Y_AXIS_MOTOR_09 //kuo exper Y axis**
//#define Z_AXIS_MOTOR_09 //kuo exper Z axis
//#define E_AXIS_MOTOR_09 //kuo exper EXTRUDER

//====== Kuo Uncomment ONLY ONE or NONE of below for geared extruders
//Don't forget to also send gcode to set e-steps as detailed earlier
//Reversion back from geared extruder requires sending M92 E280 & M500 to printer
//
//#define SKELESTRUDER // Uncomment if you have a skelestruder. Applies the patches for load distances and Z height.
//#define BMG_EXTRUDER //Kuo Uncomment for BMG 3:1 extruder. This also sets BMG height for you.
//#define EXTRUDER_GEARRATIO_30 //Kuo Uncomment for extruder with gear ratio 3.0. 
//#define EXTRUDER_GEARRATIO_3375 //Kuo Uncomment for extruder with gear ratio 3.375 like 54:16 BNBSX.
**#define EXTRUDER_GEARRATIO_35 //Kuo Uncomment for extruder with gear ratio 3.5 like 56:16 Bunny and Bear Short Ears or Skelestruder.**

//====== Kuo Slice Support
**#define SLICETHERMISTOR //uncomment for Slice Thermistor
#define SLICEMAGNUM //uncomment to increase MMU2S filament laod/unload distances for Slice Magnum**

//====== Kuo End of defines one normally needs to change ======

**Comment by cggorman** [comment]
Excellent, thanks! It compiles, uploads, and passes selftest.

Any changes needed to add MMU2 & BLTOUCH support?  

The machine is currently without, but I have those parts set aside and ready for the next wave.

**Comment by guykuo** [comment]
MMU2 maybe no. Still not enough experience to say if Magnum will need special filament move distances.

BLTouch is much larger issue to add. Current Prusa firmware completely removed support for BLTouch. You have to go to an old build or switch to generic Marlin (which of course doesn't have my 0.9 motor stuff nor MMU2 support.

**Comment by cggorman** [comment]
Hmm...  OK. I can make due without the BLTOUCH, but I have to have the MMU for soluble supports.

Thanks so much for all you do!

**Pull request merged**
